server:
    port: 9090

spring:
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    search-locations: C:/Users/nicolas/OneDrive/A3-Sistemas_Distribuidos/spring-boot-microservices/microservices/config-server/config-files