server:
    port: 9090

spring:
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    search-locations: C:/Users/nsds2/Documents/spring-boot-microservices/microservices/config-server/config-files