spring:
    datasource:
        url: jdbc:postgresql://localhost:50008/room_db
        username: "room-root"
        password: "password"
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: "true"
        hibernate:
            ddl-auto: update
        show-sql: "true"