server:
    port: 9092
    error:
        include-message: always

eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true