server:
    port: 9092
    error:
        include-message: always

eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://admin:password@localhost:8761/eureka
        register-with-eureka: true
        fetch-registry: true