spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: password

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false