server:
  port: 9093
  error:
    include-message: always

spring:
  application:
    name: room
    admin: user
  datasource:
    url: jdbc:postgresql://localhost:50008/room_db
    username: "room-root"
    password: "password"
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: "true"
      hibernate:
        ddl-auto: update
      show-sql: "true"

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true