server:
  port: 9093
  error:
    include-message: always

spring:
  application:
    admin: user
  datasource:
    url: jdbc:postgresql://localhost:50008/room
    username: "room-root"
    password: "password"
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: "true"
      hibernate:
        ddl-auto: update
      show-sql: "true"