services:
  postgres-user:
    container_name: postgres-user
    image: postgres
    environment:
      POSTGRES_USER: user-root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - user:/data/postgres
    ports:
      - "50005:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-room:
    container_name: postgres-room
    image: postgres
    environment:
      POSTGRES_USER: room-root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - room:/data/postgres
    ports:
      - "50008:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  room:
  user:
  pgadmin: